version: "3.9"

services:
  web: &web
    build: .
    volumes:
      - ".:/code:delegated"
    command: bash -c "rm -rf /code/tmp/pids && bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
